language:   c

compiler:
    - gcc
    - clang

env:
    - ENABLE_COVERAGE=false
    - ENABLE_COVERAGE=true

matrix:
    include:
        - compiler: clang
          env: ENABLE_COVERAGE=false
        - compiler: gcc
          env: ENABLE_COVERAGE=true

before_install:
    - if [ "$ENABLE_COVERAGE" == "true" ] ; then sudo pip install cpp-coveralls ; fi

script: make && make test

after_success:
    - if [ "$ENABLE_COVERAGE" == "true" ] ; then coveralls -b . -e build -e tests --gcov-options '\-lp' ; fi
